
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "username": "usertest",
    "password": "rahasia"
}


###

GET http://localhost:3000/api/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJ0ZXN0IiwiaWF0IjoxNjk3MTI3NzAxfQ.you000efT8RA5fR1pj3Kzf6k383VqZNcTdtYCKWmMCU
Content-Type: application/json


###
PATCH  http://localhost:3000/api/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYmVsYSIsInVzZXJuYW1lIjoidXNlcnRlc3QiLCJpYXQiOjE2OTcxMjMxNzF9.GYWfo8Z6WsdIUUigPxQZBmfDWMJVrD3g-N_EE2Z7JKk
Content-Type: application/json

{
    "username": "usertest",
    "password": "rahasia"
}